<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class AdditionalProductSeeder extends Seeder
{
    public function run(): void
    {
        // Get categories
        $tablets = Category::where('slug', 'tablets')->first();
        $headphones = Category::where('slug', 'headphones')->first();
        $watches = Category::where('slug', 'watches')->first();
        $accessories = Category::where('slug', 'accessories')->first();

        $products = [
            // HEADPHONES (Add 8 more unique items)
            [
                'category_id' => $headphones ? $headphones->id : 4,
                'name_uk' => 'Bose QuietComfort 45',
                'name_en' => 'Bose QuietComfort 45',
                'description_uk' => 'Легендарні навушники Bose з найкращим шумоподавленням у своєму класі.',
                'description_en' => 'Legendary Bose headphones with best-in-class noise cancellation.',
                'short_description_uk' => 'Навушники Bose з шумоподавленням',
                'short_description_en' => 'Bose headphones with noise cancellation',
                'sku' => 'BOSEQC45',
                'slug' => 'bose-quietcomfort-45',
                'price' => 11999.00,
                'quantity' => 12,
                'brand' => 'Bose',
                'model' => 'QuietComfort 45',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=41'],
                'specifications' => ['Тип' => 'Бездротові накладні', 'ANC' => 'Так', 'Час роботи' => '24 години']
            ],
            [
                'category_id' => $headphones ? $headphones->id : 4,
                'name_uk' => 'Sennheiser HD 660S2',
                'name_en' => 'Sennheiser HD 660S2',
                'description_uk' => 'Референсні відкриті навушники для аудіофілів з неперевершеною якістю звуку.',
                'description_en' => 'Reference open-back headphones for audiophiles with unparalleled sound quality.',
                'short_description_uk' => 'Аудіофільські навушники Sennheiser',
                'short_description_en' => 'Audiophile Sennheiser headphones',
                'sku' => 'SENHD660S2',
                'slug' => 'sennheiser-hd-660s2',
                'price' => 18999.00,
                'quantity' => 8,
                'brand' => 'Sennheiser',
                'model' => 'HD 660S2',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=42'],
                'specifications' => ['Тип' => 'Відкриті проводові', 'Опір' => '300 Ом', 'Частотний діапазон' => '8-41,500 Гц']
            ],
            [
                'category_id' => $headphones ? $headphones->id : 4,
                'name_uk' => 'Audio-Technica ATH-M50xBT2',
                'name_en' => 'Audio-Technica ATH-M50xBT2',
                'description_uk' => 'Професійні студійні навушники з бездротовим підключенням та відмінним звуком.',
                'description_en' => 'Professional studio headphones with wireless connectivity and excellent sound.',
                'short_description_uk' => 'Студійні навушники Audio-Technica',
                'short_description_en' => 'Audio-Technica studio headphones',
                'sku' => 'ATHM50XBT2',
                'slug' => 'audio-technica-ath-m50xbt2',
                'price' => 7999.00,
                'quantity' => 20,
                'brand' => 'Audio-Technica',
                'model' => 'ATH-M50xBT2',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=43'],
                'specifications' => ['Тип' => 'Бездротові студійні', 'Час роботи' => '50 годин', 'Кодеки' => 'AAC, LDAC']
            ],
            [
                'category_id' => $headphones ? $headphones->id : 4,
                'name_uk' => 'Beyerdynamic DT 990 Pro',
                'name_en' => 'Beyerdynamic DT 990 Pro',
                'description_uk' => 'Професійні відкриті навушники для студійної роботи та мастерингу.',
                'description_en' => 'Professional open-back headphones for studio work and mastering.',
                'short_description_uk' => 'Професійні навушники Beyerdynamic',
                'short_description_en' => 'Professional Beyerdynamic headphones',
                'sku' => 'BEYDT990PRO',
                'slug' => 'beyerdynamic-dt-990-pro',
                'price' => 5999.00,
                'quantity' => 25,
                'brand' => 'Beyerdynamic',
                'model' => 'DT 990 Pro',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=44'],
                'specifications' => ['Тип' => 'Відкриті проводові', 'Опір' => '250 Ом', 'Частотний діапазон' => '5-35,000 Гц']
            ],
            [
                'category_id' => $headphones ? $headphones->id : 4,
                'name_uk' => 'JBL Tune 760NC',
                'name_en' => 'JBL Tune 760NC',
                'description_uk' => 'Доступні бездротові навушники з активним шумоподавленням та JBL Pure Bass звуком.',
                'description_en' => 'Affordable wireless headphones with active noise cancelling and JBL Pure Bass sound.',
                'short_description_uk' => 'Бюджетні навушники JBL з ANC',
                'short_description_en' => 'Budget JBL headphones with ANC',
                'sku' => 'JBLTUNE760NC',
                'slug' => 'jbl-tune-760nc',
                'price' => 3999.00,
                'quantity' => 30,
                'brand' => 'JBL',
                'model' => 'Tune 760NC',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=45'],
                'specifications' => ['Тип' => 'Бездротові накладні', 'ANC' => 'Так', 'Час роботи' => '35 годин']
            ],
            [
                'category_id' => $headphones ? $headphones->id : 4,
                'name_uk' => 'SteelSeries Arctis 7P',
                'name_en' => 'SteelSeries Arctis 7P',
                'description_uk' => 'Ігрові бездротові навушники з просторовим звуком для PlayStation та PC.',
                'description_en' => 'Gaming wireless headphones with spatial audio for PlayStation and PC.',
                'short_description_uk' => 'Ігрові навушники SteelSeries',
                'short_description_en' => 'SteelSeries gaming headphones',
                'sku' => 'STEELARCTIS7P',
                'slug' => 'steelseries-arctis-7p',
                'price' => 6999.00,
                'quantity' => 18,
                'brand' => 'SteelSeries',
                'model' => 'Arctis 7P',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=46'],
                'specifications' => ['Тип' => 'Ігрові бездротові', 'Мікрофон' => 'Знімний', 'Час роботи' => '24 години']
            ],
            [
                'category_id' => $headphones ? $headphones->id : 4,
                'name_uk' => 'Beats Studio3 Wireless',
                'name_en' => 'Beats Studio3 Wireless',
                'description_uk' => 'Стильні навушники з адаптивним шумоподавленням та чіпом Apple W1.',
                'description_en' => 'Stylish headphones with adaptive noise cancelling and Apple W1 chip.',
                'short_description_uk' => 'Стильні навушники Beats',
                'short_description_en' => 'Stylish Beats headphones',
                'sku' => 'BEATSSTUDIO3',
                'slug' => 'beats-studio3-wireless',
                'price' => 8999.00,
                'old_price' => 10999.00,
                'quantity' => 15,
                'brand' => 'Beats',
                'model' => 'Studio3 Wireless',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=47'],
                'specifications' => ['Тип' => 'Бездротові накладні', 'ANC' => 'Адаптивне', 'Час роботи' => '22 години']
            ],
            [
                'category_id' => $headphones ? $headphones->id : 4,
                'name_uk' => 'Shure AONIC 50',
                'name_en' => 'Shure AONIC 50',
                'description_uk' => 'Преміум навушники з професійним звуком та налаштованим ANC.',
                'description_en' => 'Premium headphones with professional sound and adjustable ANC.',
                'short_description_uk' => 'Преміум навушники Shure',
                'short_description_en' => 'Premium Shure headphones',
                'sku' => 'SHUREAONIC50',
                'slug' => 'shure-aonic-50',
                'price' => 13999.00,
                'quantity' => 10,
                'brand' => 'Shure',
                'model' => 'AONIC 50',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=48'],
                'specifications' => ['Тип' => 'Бездротові накладні', 'ANC' => 'Налаштоване', 'Час роботи' => '20 годин']
            ],

            // WATCHES (Add 10 items)
            [
                'category_id' => $watches ? $watches->id : 5,
                'name_uk' => 'Apple Watch Series 9',
                'name_en' => 'Apple Watch Series 9',
                'description_uk' => 'Найновіший розумний годинник Apple з S9 чіпом та функціями охорони здоров\'я.',
                'description_en' => 'Latest Apple smartwatch with S9 chip and health monitoring features.',
                'short_description_uk' => 'Розумний годинник Apple',
                'short_description_en' => 'Apple smartwatch',
                'sku' => 'APPLEWATCH9',
                'slug' => 'apple-watch-series-9',
                'price' => 16999.00,
                'quantity' => 20,
                'brand' => 'Apple',
                'model' => 'Watch Series 9',
                'is_active' => true,
                'is_featured' => true,
                'images' => ['https://picsum.photos/600/600?random=50'],
                'specifications' => ['Екран' => 'Always-On Retina', 'Чіп' => 'S9 SiP', 'Водостійкість' => '50м']
            ],
            [
                'category_id' => $watches ? $watches->id : 5,
                'name_uk' => 'Samsung Galaxy Watch6 Classic',
                'name_en' => 'Samsung Galaxy Watch6 Classic',
                'description_uk' => 'Елегантний Android годинник з обертовим безелем та функціями фітнес-трекера.',
                'description_en' => 'Elegant Android watch with rotating bezel and fitness tracker features.',
                'short_description_uk' => 'Елегантний Samsung годинник',
                'short_description_en' => 'Elegant Samsung watch',
                'sku' => 'GALAXYWATCH6C',
                'slug' => 'samsung-galaxy-watch6-classic',
                'price' => 14999.00,
                'quantity' => 15,
                'brand' => 'Samsung',
                'model' => 'Galaxy Watch6 Classic',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=51'],
                'specifications' => ['Екран' => '1.5" Super AMOLED', 'ОС' => 'Wear OS', 'Час роботи' => '40 годин']
            ],
            [
                'category_id' => $watches ? $watches->id : 5,
                'name_uk' => 'Garmin Fenix 7X',
                'name_en' => 'Garmin Fenix 7X',
                'description_uk' => 'Професійний мультиспортивний GPS годинник для спортсменів та мандрівників.',
                'description_en' => 'Professional multisport GPS watch for athletes and adventurers.',
                'short_description_uk' => 'Спортивний GPS годинник Garmin',
                'short_description_en' => 'Garmin sports GPS watch',
                'sku' => 'GARMINFENIX7X',
                'slug' => 'garmin-fenix-7x',
                'price' => 24999.00,
                'quantity' => 10,
                'brand' => 'Garmin',
                'model' => 'Fenix 7X',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=52'],
                'specifications' => ['GPS' => 'Мульти-GNSS', 'Время роботи' => '28 днів', 'Водостійкість' => '10 ATM']
            ],
            [
                'category_id' => $watches ? $watches->id : 5,
                'name_uk' => 'Fossil Gen 6',
                'name_en' => 'Fossil Gen 6',
                'description_uk' => 'Стильний Wear OS годинник з класичним дизайном та сучасними функціями.',
                'description_en' => 'Stylish Wear OS watch with classic design and modern features.',
                'short_description_uk' => 'Стильний годинник Fossil',
                'short_description_en' => 'Stylish Fossil watch',
                'sku' => 'FOSSILGEN6',
                'slug' => 'fossil-gen-6',
                'price' => 7999.00,
                'old_price' => 9999.00,
                'quantity' => 18,
                'brand' => 'Fossil',
                'model' => 'Gen 6',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=53'],
                'specifications' => ['ОС' => 'Wear OS', 'Процесор' => 'Snapdragon Wear 4100+', 'Час роботи' => '24 години']
            ],
            [
                'category_id' => $watches ? $watches->id : 5,
                'name_uk' => 'Amazfit GTS 4',
                'name_en' => 'Amazfit GTS 4',
                'description_uk' => 'Доступний фітнес-годинник з AMOLED дисплеєм та тривалим часом роботи.',
                'description_en' => 'Affordable fitness watch with AMOLED display and long battery life.',
                'short_description_uk' => 'Фітнес-годинник Amazfit',
                'short_description_en' => 'Amazfit fitness watch',
                'sku' => 'AMAZFITGTS4',
                'slug' => 'amazfit-gts-4',
                'price' => 4999.00,
                'quantity' => 25,
                'brand' => 'Amazfit',
                'model' => 'GTS 4',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=54'],
                'specifications' => ['Екран' => '1.75" AMOLED', 'Час роботи' => '8 днів', 'Водостійкість' => '5 ATM']
            ],

            // ACCESSORIES (Add 10 items)
            [
                'category_id' => $accessories ? $accessories->id : 6,
                'name_uk' => 'Anker PowerCore 10000',
                'name_en' => 'Anker PowerCore 10000',
                'description_uk' => 'Компактний портативний зарядний пристрій з швидкою зарядкою PowerIQ.',
                'description_en' => 'Compact portable charger with PowerIQ fast charging technology.',
                'short_description_uk' => 'Портативна зарядка Anker 10000мАг',
                'short_description_en' => 'Anker portable charger 10000mAh',
                'sku' => 'ANKERPOWERCORE10K',
                'slug' => 'anker-powercore-10000',
                'price' => 1299.00,
                'quantity' => 50,
                'brand' => 'Anker',
                'model' => 'PowerCore 10000',
                'is_active' => true,
                'is_featured' => true,
                'images' => ['https://picsum.photos/600/600?random=60'],
                'specifications' => ['Ємність' => '10000 мАг', 'Вихід' => 'USB-A x2', 'Швидка зарядка' => 'PowerIQ 2.0']
            ],
            [
                'category_id' => $accessories ? $accessories->id : 6,
                'name_uk' => 'Belkin 3-in-1 Wireless Charger',
                'name_en' => 'Belkin 3-in-1 Wireless Charger',
                'description_uk' => 'Бездротова зарядна станція для iPhone, Apple Watch та AirPods одночасно.',
                'description_en' => 'Wireless charging station for iPhone, Apple Watch and AirPods simultaneously.',
                'short_description_uk' => 'Бездротова зарядка 3-в-1 Belkin',
                'short_description_en' => 'Belkin 3-in-1 wireless charger',
                'sku' => 'BELKIN3IN1WIRELESS',
                'slug' => 'belkin-3-in-1-wireless-charger',
                'price' => 3999.00,
                'quantity' => 25,
                'brand' => 'Belkin',
                'model' => '3-in-1 Wireless Charger',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=61'],
                'specifications' => ['Підтримка' => 'iPhone, Apple Watch, AirPods', 'Потужність' => '15W', 'MagSafe' => 'Сумісний']
            ],
            [
                'category_id' => $accessories ? $accessories->id : 6,
                'name_uk' => 'Logitech MX Master 3S',
                'name_en' => 'Logitech MX Master 3S',
                'description_uk' => 'Професійна бездротова миша з точним трекінгом та ергономічним дизайном.',
                'description_en' => 'Professional wireless mouse with precise tracking and ergonomic design.',
                'short_description_uk' => 'Професійна миша Logitech',
                'short_description_en' => 'Professional Logitech mouse',
                'sku' => 'LOGIMXMASTER3S',
                'slug' => 'logitech-mx-master-3s',
                'price' => 3499.00,
                'quantity' => 30,
                'brand' => 'Logitech',
                'model' => 'MX Master 3S',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=62'],
                'specifications' => ['DPI' => '8000', 'Підключення' => 'USB-C, Bluetooth', 'Час роботи' => '70 днів']
            ],
            [
                'category_id' => $accessories ? $accessories->id : 6,
                'name_uk' => 'Apple Magic Keyboard',
                'name_en' => 'Apple Magic Keyboard',
                'description_uk' => 'Бездротова клавіатура Apple з механізмом "ножиці" та Touch ID.',
                'description_en' => 'Apple wireless keyboard with scissor mechanism and Touch ID.',
                'short_description_uk' => 'Бездротова клавіатура Apple',
                'short_description_en' => 'Apple wireless keyboard',
                'sku' => 'APPLEMAGICKEYBOARD',
                'slug' => 'apple-magic-keyboard',
                'price' => 5999.00,
                'quantity' => 20,
                'brand' => 'Apple',
                'model' => 'Magic Keyboard',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=63'],
                'specifications' => ['Підключення' => 'Lightning/USB-C', 'Touch ID' => 'Так', 'Раскладка' => 'US/Ukrainian']
            ],
            [
                'category_id' => $accessories ? $accessories->id : 6,
                'name_uk' => 'Samsung T7 Portable SSD 1TB',
                'name_en' => 'Samsung T7 Portable SSD 1TB',
                'description_uk' => 'Швидкий портативний SSD з захистом паролем та USB 3.2 Gen 2.',
                'description_en' => 'Fast portable SSD with password protection and USB 3.2 Gen 2.',
                'short_description_uk' => 'Портативний SSD Samsung 1TB',
                'short_description_en' => 'Samsung portable SSD 1TB',
                'sku' => 'SAMSUNGT7SSD1TB',
                'slug' => 'samsung-t7-portable-ssd-1tb',
                'price' => 4299.00,
                'quantity' => 15,
                'brand' => 'Samsung',
                'model' => 'T7 Portable SSD',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=64'],
                'specifications' => ['Ємність' => '1TB', 'Швидкість' => 'до 1050 МБ/с', 'Підключення' => 'USB 3.2 Gen 2']
            ],
            [
                'category_id' => $accessories ? $accessories->id : 6,
                'name_uk' => 'Spigen Tough Armor Case',
                'name_en' => 'Spigen Tough Armor Case',
                'description_uk' => 'Захисний чохол з подвійним захистом та підставкою для смартфона.',
                'description_en' => 'Protective case with dual protection and kickstand for smartphone.',
                'short_description_uk' => 'Захисний чохол Spigen',
                'short_description_en' => 'Spigen protective case',
                'sku' => 'SPIGENTOUGHARMOR',
                'slug' => 'spigen-tough-armor-case',
                'price' => 899.00,
                'quantity' => 40,
                'brand' => 'Spigen',
                'model' => 'Tough Armor',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=65'],
                'specifications' => ['Захист' => 'Подвійний шар', 'Підставка' => 'Так', 'Сумісність' => 'iPhone/Samsung']
            ],
            [
                'category_id' => $accessories ? $accessories->id : 6,
                'name_uk' => 'UGREEN USB-C Hub 6-in-1',
                'name_en' => 'UGREEN USB-C Hub 6-in-1',
                'description_uk' => 'Багатофункціональний USB-C хаб з HDMI, USB 3.0 та PD зарядкою.',
                'description_en' => 'Multifunctional USB-C hub with HDMI, USB 3.0 and PD charging.',
                'short_description_uk' => 'USB-C хаб UGREEN 6-в-1',
                'short_description_en' => 'UGREEN USB-C hub 6-in-1',
                'sku' => 'UGREENUSBC6IN1',
                'slug' => 'ugreen-usb-c-hub-6-in-1',
                'price' => 1599.00,
                'quantity' => 35,
                'brand' => 'UGREEN',
                'model' => 'USB-C Hub 6-in-1',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=66'],
                'specifications' => ['Порти' => 'HDMI, USB 3.0 x3, PD, SD', 'HDMI' => '4K@60Hz', 'PD зарядка' => '100W']
            ],
            [
                'category_id' => $accessories ? $accessories->id : 6,
                'name_uk' => 'Razer DeathAdder V3',
                'name_en' => 'Razer DeathAdder V3',
                'description_uk' => 'Ігрова миша з сенсором Focus Pro 30K та перемикачами Gen-3.',
                'description_en' => 'Gaming mouse with Focus Pro 30K sensor and Gen-3 switches.',
                'short_description_uk' => 'Ігрова миша Razer',
                'short_description_en' => 'Razer gaming mouse',
                'sku' => 'RAZERDEATHADDERV3',
                'slug' => 'razer-deathadder-v3',
                'price' => 2499.00,
                'quantity' => 25,
                'brand' => 'Razer',
                'model' => 'DeathAdder V3',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=67'],
                'specifications' => ['DPI' => '30000', 'Сенсор' => 'Focus Pro 30K', 'Кнопки' => '8']
            ],
            [
                'category_id' => $accessories ? $accessories->id : 6,
                'name_uk' => 'Peak Design Everyday Backpack',
                'name_en' => 'Peak Design Everyday Backpack',
                'description_uk' => 'Модульний рюкзак для фотографа з швидким доступом та захистом від дощу.',
                'description_en' => 'Modular photographer backpack with quick access and rain protection.',
                'short_description_uk' => 'Рюкзак Peak Design для фотографа',
                'short_description_en' => 'Peak Design photographer backpack',
                'sku' => 'PEAKDESIGNBACKPACK',
                'slug' => 'peak-design-everyday-backpack',
                'price' => 8999.00,
                'quantity' => 10,
                'brand' => 'Peak Design',
                'model' => 'Everyday Backpack',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=68'],
                'specifications' => ['Об\'єм' => '20L', 'Модульність' => 'FlexFold', 'Захист' => 'Від дощу']
            ],
            [
                'category_id' => $accessories ? $accessories->id : 6,
                'name_uk' => 'Twelve South BookBook Case',
                'name_en' => 'Twelve South BookBook Case',
                'description_uk' => 'Шкіряний чохол-книжка з відділеннями для карток та готівки.',
                'description_en' => 'Leather book-style case with compartments for cards and cash.',
                'short_description_uk' => 'Шкіряний чохол-книжка',
                'short_description_en' => 'Leather book case',
                'sku' => 'TWELVESOUTHBOOKBOOK',
                'slug' => 'twelve-south-bookbook-case',
                'price' => 2299.00,
                'quantity' => 20,
                'brand' => 'Twelve South',
                'model' => 'BookBook',
                'is_active' => true,
                'images' => ['https://picsum.photos/600/600?random=69'],
                'specifications' => ['Матеріал' => 'Натуральна шкіра', 'Кишені' => 'Картки, готівка', 'Підставка' => 'Так']
            ],
        ];

        foreach ($products as $productData) {
            Product::create([
                'category_id' => $productData['category_id'],
                'name_uk' => $productData['name_uk'],
                'name_en' => $productData['name_en'],
                'description_uk' => $productData['description_uk'],
                'description_en' => $productData['description_en'],
                'short_description_uk' => $productData['short_description_uk'],
                'short_description_en' => $productData['short_description_en'],
                'sku' => $productData['sku'],
                'slug' => $productData['slug'],
                'price' => $productData['price'],
                'old_price' => $productData['old_price'] ?? null,
                'quantity' => $productData['quantity'],
                'brand' => $productData['brand'],
                'model' => $productData['model'],
                'is_active' => $productData['is_active'],
                'is_featured' => $productData['is_featured'] ?? false,
                'images' => json_encode($productData['images']),
                'specifications' => json_encode($productData['specifications']),
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->command->info('Додано ' . count($products) . ' додаткових товарів успішно!');
    }
}
