<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ComprehensiveProductSeeder extends Seeder
{
    public function run(): void
    {
        // Get categories
        $smartphones = Category::where('slug', 'smartphones')->first();
        $laptops = Category::where('slug', 'laptops')->first();
        $tablets = Category::where('slug', 'tablets')->first();
        $headphones = Category::where('slug', 'headphones')->first();
        $watches = Category::where('slug', 'watches')->first();
        $accessories = Category::where('slug', 'accessories')->first();

        // Clear existing products
        Product::truncate();

        $products = [
            // SMARTPHONES (10 items)
            [
                'category_id' => $smartphones ? $smartphones->id : 1,
                'name_uk' => 'iPhone 15 Pro',
                'name_en' => 'iPhone 15 Pro',
                'description_uk' => 'Найновіший флагманський смартфон від Apple з потужним процесором A17 Pro та професійною камерою. Титановий корпус забезпечує міцність і легкість.',
                'description_en' => 'Latest flagship smartphone from Apple with powerful A17 Pro processor and professional camera.',
                'short_description_uk' => 'Флагманський смартфон Apple з титановим корпусом',
                'short_description_en' => 'Apple flagship smartphone with titanium body',
                'sku' => 'IPHONE15PRO128',
                'slug' => 'iphone-15-pro',
                'price' => 45999.00,
                'old_price' => 49999.00,
                'quantity' => 25,
                'brand' => 'Apple',
                'model' => 'iPhone 15 Pro',
                'is_active' => true,
                'is_featured' => true,
                'images' => ['https://picsum.photos/600/600?random=1'],
                'specifications' => ['Екран' => '6.1" Super Retina XDR', 'Процесор' => 'A17 Pro', 'Память' => '128GB']
            ],
            [
                'category_id' => $smartphones ? $smartphones->id : 1,
                'name_uk' => 'Samsung Galaxy S24 Ultra',
                'name_en' => 'Samsung Galaxy S24 Ultra',
                'description_uk' => 'Потужний Android-смартфон з S Pen та професійною камерою 200MP. Найкращий для продуктивності та творчості.',
                'description_en' => 'Powerful Android smartphone with S Pen and professional 200MP camera.',
                'short_description_uk' => 'Топовий Android з S Pen і камерою 200MP',
                'short_description_en' => 'Top Android with S Pen and 200MP camera',
                'sku' => 'GALAXY-S24-ULTRA',
                'slug' => 'samsung-galaxy-s24-ultra',
                'price' => 42999.00,
                'quantity' => 18,
                'brand' => 'Samsung',
                'model' => 'Galaxy S24 Ultra',
                'is_active' => true,
                'is_featured' => true,
                'images' => ['https://picsum.photos/600/600?random=2'],
                'specifications' => ['Екран' => '6.8" Dynamic AMOLED 2X', 'Процесор' => 'Snapdragon 8 Gen 3', 'Память' => '256GB']
            ],
            [
                'category_id' => $smartphones ? $smartphones->id : 1,
                'name_uk' => 'iPhone 15',
                'name_en' => 'iPhone 15',
                'description_uk' => 'Класичний iPhone 15 з USB-C та покращеною камерою. Ідеальний баланс функцій та ціни.',
                'description_en' => 'Classic iPhone 15 with USB-C and improved camera.',
                'short_description_uk' => 'Класичний iPhone з USB-C',
                'short_description_en' => 'Classic iPhone with USB-C',
                'sku' => 'IPHONE15-128',
                'slug' => 'iphone-15',
                'price' => 36999.00,
                'old_price' => 39999.00,
                'quantity' => 30,
                'brand' => 'Apple',
                'model' => 'iPhone 15',
                'is_active' => true,
                'is_featured' => false,
                'images' => ['https://picsum.photos/600/600?random=3'],
                'specifications' => ['Екран' => '6.1" Super Retina XDR', 'Процесор' => 'A16 Bionic', 'Память' => '128GB']
            ],
            [
                'category_id' => $smartphones ? $smartphones->id : 1,
                'name_uk' => 'Google Pixel 8 Pro',
                'name_en' => 'Google Pixel 8 Pro',
                'description_uk' => 'Смартфон Google з найкращою камерою та чистим Android. Штучний інтелект у кожному кадрі.',
                'description_en' => 'Google smartphone with the best camera and pure Android.',
                'short_description_uk' => 'Найкраща камера від Google',
                'short_description_en' => 'Best camera from Google',
                'sku' => 'PIXEL8PRO-256',
                'slug' => 'google-pixel-8-pro',
                'price' => 38999.00,
                'quantity' => 15,
                'brand' => 'Google',
                'model' => 'Pixel 8 Pro',
                'is_active' => true,
                'is_featured' => false,
                'images' => ['https://picsum.photos/600/600?random=4'],
                'specifications' => ['Екран' => '6.7" LTPO OLED', 'Процесор' => 'Google Tensor G3', 'Память' => '256GB']
            ],
            [
                'category_id' => $smartphones ? $smartphones->id : 1,
                'name_uk' => 'OnePlus 12',
                'name_en' => 'OnePlus 12',
                'description_uk' => 'Швидкий смартфон з потужним процесором та швидкою зарядкою 100W. Для тих, хто цінує швидкість.',
                'description_en' => 'Fast smartphone with powerful processor and 100W fast charging.',
                'short_description_uk' => 'Швидкість у всьому - OnePlus 12',
                'short_description_en' => 'Speed in everything - OnePlus 12',
                'sku' => 'ONEPLUS12-256',
                'slug' => 'oneplus-12',
                'price' => 33999.00,
                'old_price' => 36999.00,
                'quantity' => 20,
                'brand' => 'OnePlus',
                'model' => 'OnePlus 12',
                'is_active' => true,
                'is_featured' => true,
                'images' => ['https://picsum.photos/600/600?random=5'],
                'specifications' => ['Екран' => '6.82" LTPO AMOLED', 'Процесор' => 'Snapdragon 8 Gen 3', 'Память' => '256GB']
            ],
            [
                'category_id' => $smartphones ? $smartphones->id : 1,
                'name_uk' => 'Xiaomi 14 Ultra',
                'name_en' => 'Xiaomi 14 Ultra',
                'description_uk' => 'Топовий смартфон Xiaomi з камерою Leica та металевим корпусом. Преміум якість за розумну ціну.',
                'description_en' => 'Top Xiaomi smartphone with Leica camera and metal body.',
                'short_description_uk' => 'Преміум Xiaomi з камерою Leica',
                'short_description_en' => 'Premium Xiaomi with Leica camera',
                'sku' => 'XIAOMI14ULTRA',
                'slug' => 'xiaomi-14-ultra',
                'price' => 31999.00,
                'quantity' => 22,
                'brand' => 'Xiaomi',
                'model' => '14 Ultra',
                'is_active' => true,
                'is_featured' => false,
                'images' => ['https://picsum.photos/600/600?random=6'],
                'specifications' => ['Екран' => '6.73" LTPO AMOLED', 'Процесор' => 'Snapdragon 8 Gen 3', 'Память' => '512GB']
            ],
            [
                'category_id' => $smartphones ? $smartphones->id : 1,
                'name_uk' => 'Huawei P60 Pro',
                'name_en' => 'Huawei P60 Pro',
                'description_uk' => 'Елегантний смартфон з відмінною камерою та стильним дизайном. Акцент на фотографії та естетиці.',
                'description_en' => 'Elegant smartphone with excellent camera and stylish design.',
                'short_description_uk' => 'Елегантність і стиль від Huawei',
                'short_description_en' => 'Elegance and style from Huawei',
                'sku' => 'HUAWEI-P60PRO',
                'slug' => 'huawei-p60-pro',
                'price' => 29999.00,
                'old_price' => 32999.00,
                'quantity' => 17,
                'brand' => 'Huawei',
                'model' => 'P60 Pro',
                'is_active' => true,
                'is_featured' => false,
                'images' => ['https://picsum.photos/600/600?random=7'],
                'specifications' => ['Екран' => '6.67" LTPO OLED', 'Процесор' => 'Snapdragon 8+ Gen 1', 'Память' => '256GB']
            ],
            [
                'category_id' => $smartphones ? $smartphones->id : 1,
                'name_uk' => 'Nothing Phone (2)',
                'name_en' => 'Nothing Phone (2)',
                'description_uk' => 'Унікальний смартфон з прозорим дизайном та Glyph-підсвіткою. Інновація та стиль в одному пристрої.',
                'description_en' => 'Unique smartphone with transparent design and Glyph lighting.',
                'short_description_uk' => 'Унікальний дизайн з Glyph-підсвіткою',
                'short_description_en' => 'Unique design with Glyph lighting',
                'sku' => 'NOTHING-PHONE2',
                'slug' => 'nothing-phone-2',
                'price' => 25999.00,
                'quantity' => 12,
                'brand' => 'Nothing',
                'model' => 'Phone (2)',
                'is_active' => true,
                'is_featured' => false,
                'images' => ['https://picsum.photos/600/600?random=8'],
                'specifications' => ['Екран' => '6.7" LTPO OLED', 'Процесор' => 'Snapdragon 8+ Gen 1', 'Память' => '256GB']
            ],
            [
                'category_id' => $smartphones ? $smartphones->id : 1,
                'name_uk' => 'Sony Xperia 1 V',
                'name_en' => 'Sony Xperia 1 V',
                'description_uk' => 'Професійний смартфон для фотографів з камерою Alpha та 4K дисплеєм. Якість Sony у вашій кишені.',
                'description_en' => 'Professional smartphone for photographers with Alpha camera and 4K display.',
                'short_description_uk' => 'Професійна камера Sony Alpha',
                'short_description_en' => 'Professional Sony Alpha camera',
                'sku' => 'SONY-XPERIA1V',
                'slug' => 'sony-xperia-1-v',
                'price' => 34999.00,
                'quantity' => 8,
                'brand' => 'Sony',
                'model' => 'Xperia 1 V',
                'is_active' => true,
                'is_featured' => false,
                'images' => ['https://picsum.photos/600/600?random=9'],
                'specifications' => ['Екран' => '6.5" 4K OLED', 'Процесор' => 'Snapdragon 8 Gen 2', 'Память' => '256GB']
            ],
            [
                'category_id' => $smartphones ? $smartphones->id : 1,
                'name_uk' => 'Asus ROG Phone 8',
                'name_en' => 'Asus ROG Phone 8',
                'description_uk' => 'Ігровий смартфон з вентиляторами охолодження та підсвіткою RGB. Максимальна продуктивність для геймерів.',
                'description_en' => 'Gaming smartphone with cooling fans and RGB lighting.',
                'short_description_uk' => 'Ігровий смартфон з RGB підсвіткою',
                'short_description_en' => 'Gaming smartphone with RGB lighting',
                'sku' => 'ASUS-ROG8',
                'slug' => 'asus-rog-phone-8',
                'price' => 32999.00,
                'old_price' => 35999.00,
                'quantity' => 14,
                'brand' => 'Asus',
                'model' => 'ROG Phone 8',
                'is_active' => true,
                'is_featured' => false,
                'images' => ['https://picsum.photos/600/600?random=10'],
                'specifications' => ['Екран' => '6.78" AMOLED 165Hz', 'Процесор' => 'Snapdragon 8 Gen 3', 'Память' => '512GB']
            ],

            // LAPTOPS (10 items)
            [
                'category_id' => $laptops ? $laptops->id : 2,
                'name_uk' => 'MacBook Air M3',
                'name_en' => 'MacBook Air M3',
                'description_uk' => 'Ультратонкий ноутбук Apple з чіпом M3 для професійної роботи та розваг. Неймовірна продуктивність при мінімальному споживанні енергії.',
                'description_en' => 'Ultra-thin Apple laptop with M3 chip for professional work and entertainment.',
                'short_description_uk' => 'Легкий ноутбук Apple з чіпом M3',
                'short_description_en' => 'Lightweight Apple laptop with M3 chip',
                'sku' => 'MACBOOK-AIR-M3',
                'slug' => 'macbook-air-m3',
                'price' => 54999.00,
                'quantity' => 12,
                'brand' => 'Apple',
                'model' => 'MacBook Air M3',
                'is_active' => true,
                'is_featured' => true,
                'images' => ['https://picsum.photos/600/600?random=11'],
                'specifications' => ['Процесор' => 'Apple M3', 'Екран' => '13.6" Liquid Retina', 'Память' => '256GB SSD', 'RAM' => '8GB']
            ],
            [
                'category_id' => $laptops ? $laptops->id : 2,
                'name_uk' => 'ASUS ROG Strix G15',
                'name_en' => 'ASUS ROG Strix G15',
                'description_uk' => 'Ігровий ноутбук з потужною графікою RTX 4060 для сучасних ігор. Високоякісний дисплей 144Hz для плавного геймплею.',
                'description_en' => 'Gaming laptop with powerful RTX 4060 graphics for modern games.',
                'short_description_uk' => 'Ігровий ноутбук з RTX 4060',
                'short_description_en' => 'Gaming laptop with RTX 4060',
                'sku' => 'ASUS-ROG-G15',
                'slug' => 'asus-rog-strix-g15',
                'price' => 39999.00,
                'old_price' => 44999.00,
                'quantity' => 8,
                'brand' => 'ASUS',
                'model' => 'ROG Strix G15',
                'is_active' => true,
                'is_featured' => true,
                'images' => ['https://picsum.photos/600/600?random=12'],
                'specifications' => ['Процесор' => 'AMD Ryzen 7 7735HS', 'Відеокарта' => 'RTX 4060 8GB', 'RAM' => '16GB DDR5', 'SSD' => '512GB']
            ],
            [
                'category_id' => $laptops ? $laptops->id : 2,
                'name_uk' => 'Dell XPS 13',
                'name_en' => 'Dell XPS 13',
                'description_uk' => 'Компактний бізнес-ноутбук з преміум дизайном та відмінною продуктивністю. Ідеальний для роботи та навчання.',
                'description_en' => 'Compact business laptop with premium design and excellent performance.',
                'short_description_uk' => 'Преміум бізнес-ноутбук Dell',
                'short_description_en' => 'Premium Dell business laptop',
                'sku' => 'DELL-XPS13',
                'slug' => 'dell-xps-13',
                'price' => 42999.00,
                'quantity' => 15,
                'brand' => 'Dell',
                'model' => 'XPS 13',
                'is_active' => true,
                'is_featured' => false,
                'images' => ['https://picsum.photos/600/600?random=13'],
                'specifications' => ['Процесор' => 'Intel Core i7-1360P', 'Екран' => '13.4" FHD+', 'RAM' => '16GB', 'SSD' => '512GB']
            ],
            [
                'category_id' => $laptops ? $laptops->id : 2,
                'name_uk' => 'HP Spectre x360',
                'name_en' => 'HP Spectre x360',
                'description_uk' => 'Трансформер 2-в-1 з сенсорним екраном та підтримкою стилуса. Гнучкість для будь-яких завдань.',
                'description_en' => '2-in-1 transformer with touchscreen and stylus support.',
                'short_description_uk' => 'Трансформер 2-в-1 з сенсорним екраном',
                'short_description_en' => '2-in-1 transformer with touchscreen',
                'sku' => 'HP-SPECTRE-X360',
                'slug' => 'hp-spectre-x360',
                'price' => 47999.00,
                'old_price' => 51999.00,
                'quantity' => 10,
                'brand' => 'HP',
                'model' => 'Spectre x360',
                'is_active' => true,
                'is_featured' => false,
                'images' => ['https://picsum.photos/600/600?random=14'],
                'specifications' => ['Процесор' => 'Intel Core i7-1355U', 'Екран' => '13.5" OLED Touch', 'RAM' => '16GB', 'SSD' => '1TB']
            ],
            [
                'category_id' => $laptops ? $laptops->id : 2,
                'name_uk' => 'Lenovo ThinkPad X1 Carbon',
                'name_en' => 'Lenovo ThinkPad X1 Carbon',
                'description_uk' => 'Надійний бізнес-ноутбук з військовим стандартом міцності. Легкий карбоновий корпус та відмінна клавіатура.',
                'description_en' => 'Reliable business laptop with military-grade durability.',
                'short_description_uk' => 'Надійний ThinkPad з карбоновим корпусом',
                'short_description_en' => 'Reliable ThinkPad with carbon body',
                'sku' => 'LENOVO-X1-CARBON',
                'slug' => 'lenovo-thinkpad-x1-carbon',
                'price' => 52999.00,
                'quantity' => 7,
                'brand' => 'Lenovo',
                'model' => 'ThinkPad X1 Carbon',
                'is_active' => true,
                'is_featured' => false,
                'images' => ['https://picsum.photos/600/600?random=15'],
                'specifications' => ['Процесор' => 'Intel Core i7-1365U', 'Екран' => '14" WUXGA', 'RAM' => '32GB', 'SSD' => '1TB']
            ],
            [
                'category_id' => $laptops ? $laptops->id : 2,
                'name_uk' => 'Acer Predator Helios 16',
                'name_en' => 'Acer Predator Helios 16',
                'description_uk' => 'Потужний ігровий ноутбук для ентузіастів. Топова графіка RTX 4070 та швидкий дисплей 240Hz.',
                'description_en' => 'Powerful gaming laptop for enthusiasts.',
                'short_description_uk' => 'Потужний геймінг з RTX 4070',
                'short_description_en' => 'Powerful gaming with RTX 4070',
                'sku' => 'ACER-PREDATOR-16',
                'slug' => 'acer-predator-helios-16',
                'price' => 57999.00,
                'old_price' => 62999.00,
                'quantity' => 5,
                'brand' => 'Acer',
                'model' => 'Predator Helios 16',
                'is_active' => true,
                'is_featured' => true,
                'images' => ['https://picsum.photos/600/600?random=16'],
                'specifications' => ['Процесор' => 'Intel Core i7-13700HX', 'Відеокарта' => 'RTX 4070 8GB', 'RAM' => '32GB', 'SSD' => '1TB']
            ],
            [
                'category_id' => $laptops ? $laptops->id : 2,
                'name_uk' => 'MSI Creator Z17',
                'name_en' => 'MSI Creator Z17',
                'description_uk' => 'Ноутбук для творців з каліброваним дисплеєм 4K та потужною графікою. Ідеальний для відео-монтажу та дизайну.',
                'description_en' => 'Laptop for creators with calibrated 4K display and powerful graphics.',
                'short_description_uk' => 'Для творців з дисплеєм 4K',
                'short_description_en' => 'For creators with 4K display',
                'sku' => 'MSI-CREATOR-Z17',
                'slug' => 'msi-creator-z17',
                'price' => 64999.00,
                'quantity' => 6,
                'brand' => 'MSI',
                'model' => 'Creator Z17',
                'is_active' => true,
                'is_featured' => false,
                'images' => ['https://picsum.photos/600/600?random=17'],
                'specifications' => ['Процесор' => 'Intel Core i9-13900H', 'Відеокарта' => 'RTX 4060 8GB', 'RAM' => '32GB', 'SSD' => '2TB']
            ],
            [
                'category_id' => $laptops ? $laptops->id : 2,
                'name_uk' => 'Surface Laptop 5',
                'name_en' => 'Surface Laptop 5',
                'description_uk' => 'Елегантний ноутбук Microsoft з сенсорним екраном та алькантаровою клавіатурою. Стиль та функціональність.',
                'description_en' => 'Elegant Microsoft laptop with touchscreen and Alcantara keyboard.',
                'short_description_uk' => 'Елегантний Surface з алькантарою',
                'short_description_en' => 'Elegant Surface with Alcantara',
                'sku' => 'SURFACE-LAPTOP5',
                'slug' => 'surface-laptop-5',
                'price' => 46999.00,
                'quantity' => 9,
                'brand' => 'Microsoft',
                'model' => 'Surface Laptop 5',
                'is_active' => true,
                'is_featured' => false,
                'images' => ['https://picsum.photos/600/600?random=18'],
                'specifications' => ['Процесор' => 'Intel Core i7-1255U', 'Екран' => '13.5" PixelSense Touch', 'RAM' => '16GB', 'SSD' => '512GB']
            ],
            [
                'category_id' => $laptops ? $laptops->id : 2,
                'name_uk' => 'Razer Blade 15',
                'name_en' => 'Razer Blade 15',
                'description_uk' => 'Тонкий ігровий ноутбук з преміум матеріалами та RGB клавіатурою Chroma. Геймінг у стильному корпусі.',
                'description_en' => 'Thin gaming laptop with premium materials and RGB Chroma keyboard.',
                'short_description_uk' => 'Тонкий геймінг з RGB Chroma',
                'short_description_en' => 'Thin gaming with RGB Chroma',
                'sku' => 'RAZER-BLADE15',
                'slug' => 'razer-blade-15',
                'price' => 59999.00,
                'old_price' => 64999.00,
                'quantity' => 4,
                'brand' => 'Razer',
                'model' => 'Blade 15',
                'is_active' => true,
                'is_featured' => false,
                'images' => ['https://picsum.photos/600/600?random=19'],
                'specifications' => ['Процесор' => 'Intel Core i7-13800H', 'Відеокарта' => 'RTX 4060 8GB', 'RAM' => '16GB', 'SSD' => '1TB']
            ],
            [
                'category_id' => $laptops ? $laptops->id : 2,
                'name_uk' => 'Framework Laptop 13',
                'name_en' => 'Framework Laptop 13',
                'description_uk' => 'Модульний ноутбук, який можна легко ремонтувати та модернізувати. Революція у світі портативних комп\'ютерів.',
                'description_en' => 'Modular laptop that can be easily repaired and upgraded.',
                'short_description_uk' => 'Модульний ноутбук для модернізації',
                'short_description_en' => 'Modular laptop for upgrades',
                'sku' => 'FRAMEWORK-13',
                'slug' => 'framework-laptop-13',
                'price' => 38999.00,
                'quantity' => 11,
                'brand' => 'Framework',
                'model' => 'Laptop 13',
                'is_active' => true,
                'is_featured' => false,
                'images' => ['https://picsum.photos/600/600?random=20'],
                'specifications' => ['Процесор' => 'Intel Core i7-1360P', 'Екран' => '13.5" 2256x1504', 'RAM' => '16GB', 'SSD' => '512GB']
            ],

            // Continue with other categories...
            // I'll add a few more products for tablets and headphones to demonstrate

            // TABLETS (10 items)
            [
                'category_id' => $tablets ? $tablets->id : 3,
                'name_uk' => 'iPad Pro 12.9"',
                'name_en' => 'iPad Pro 12.9"',
                'description_uk' => 'Професійний планшет Apple з чіпом M2 для творчості та продуктивності. Підтримка Apple Pencil 2 покоління.',
                'description_en' => 'Professional Apple tablet with M2 chip for creativity and productivity.',
                'short_description_uk' => 'Професійний планшет з чіпом M2',
                'short_description_en' => 'Professional tablet with M2 chip',
                'sku' => 'IPAD-PRO-12',
                'slug' => 'ipad-pro-12-9',
                'price' => 52999.00,
                'quantity' => 15,
                'brand' => 'Apple',
                'model' => 'iPad Pro 12.9"',
                'is_active' => true,
                'is_featured' => true,
                'images' => ['https://picsum.photos/600/600?random=21'],
                'specifications' => ['Процесор' => 'Apple M2', 'Екран' => '12.9" Liquid Retina XDR', 'Память' => '256GB']
            ],
            [
                'category_id' => $tablets ? $tablets->id : 3,
                'name_uk' => 'Samsung Galaxy Tab S9 Ultra',
                'name_en' => 'Samsung Galaxy Tab S9 Ultra',
                'description_uk' => 'Величезний Android планшет з S Pen в комплекті. Ідеальний для роботи та розваг на великому екрані.',
                'description_en' => 'Huge Android tablet with S Pen included.',
                'short_description_uk' => 'Величезний планшет з S Pen',
                'short_description_en' => 'Huge tablet with S Pen',
                'sku' => 'GALAXY-TAB-S9-ULTRA',
                'slug' => 'samsung-galaxy-tab-s9-ultra',
                'price' => 47999.00,
                'old_price' => 52999.00,
                'quantity' => 12,
                'brand' => 'Samsung',
                'model' => 'Galaxy Tab S9 Ultra',
                'is_active' => true,
                'is_featured' => true,
                'images' => ['https://picsum.photos/600/600?random=22'],
                'specifications' => ['Процесор' => 'Snapdragon 8 Gen 2', 'Екран' => '14.6" Dynamic AMOLED 2X', 'Память' => '256GB']
            ],

            // HEADPHONES (10 items)
            [
                'category_id' => $headphones ? $headphones->id : 4,
                'name_uk' => 'Sony WH-1000XM5',
                'name_en' => 'Sony WH-1000XM5',
                'description_uk' => 'Бездротові навушники з активним шумозаглушенням та Hi-Res аудіо. Найкраще звучання від Sony.',
                'description_en' => 'Wireless headphones with active noise cancellation and Hi-Res audio.',
                'short_description_uk' => 'Преміум навушники з шумозаглушенням',
                'short_description_en' => 'Premium headphones with noise cancellation',
                'sku' => 'SONY-WH1000XM5',
                'slug' => 'sony-wh-1000xm5',
                'price' => 12999.00,
                'old_price' => 14999.00,
                'quantity' => 30,
                'brand' => 'Sony',
                'model' => 'WH-1000XM5',
                'is_active' => true,
                'is_featured' => true,
                'images' => ['https://picsum.photos/600/600?random=23'],
                'specifications' => ['Тип' => 'Накладні бездротові', 'Підключення' => 'Bluetooth 5.2', 'Батарея' => 'До 30 годин']
            ],
            [
                'category_id' => $headphones ? $headphones->id : 4,
                'name_uk' => 'AirPods Pro 2',
                'name_en' => 'AirPods Pro 2',
                'description_uk' => 'Бездротові навушники Apple з адаптивним шумозаглушенням та просторовим звуком.',
                'description_en' => 'Wireless Apple earphones with adaptive noise cancellation and spatial audio.',
                'short_description_uk' => 'Бездротові вкладиші Apple',
                'short_description_en' => 'Wireless Apple earphones',
                'sku' => 'AIRPODS-PRO2',
                'slug' => 'airpods-pro-2',
                'price' => 9999.00,
                'quantity' => 45,
                'brand' => 'Apple',
                'model' => 'AirPods Pro 2',
                'is_active' => true,
                'is_featured' => true,
                'images' => ['https://picsum.photos/600/600?random=24'],
                'specifications' => ['Тип' => 'Вкладиші TWS', 'Підключення' => 'Bluetooth 5.3', 'Батарея' => 'До 6 годин + кейс']
            ],
        ];

        foreach ($products as $productData) {
            Product::create($productData);
        }

        echo "Створено " . count($products) . " товарів успішно!\n";
    }
}
